### ISSUE TITLE
Is there a collision detection event for Collision2D? 

### ISSUE THREAD

**Issue by Kimserey** [xamarin/urho#116]
I was hoping to find something like `SubscribeToNodeCollision2D` which would work with `CollisionX2D` components.
I looked through the feature samples and only managed to find `SubscribeToNodeCollisionStart` function which works with `CollisionShape`.

**Comment by sushihangover** [comment]
_My 2 cents, change available ;-)_

Most game engines allow you to subscribe to collision events/signals/triggers at the physics engine level as applying events to each object does not scale very well (imagine your particle emitter creating 1000 water particles/sec from a fountain and also having to instance and attach individual events to each of them to detect when they collide with the fountain's pool after succumbing to gravity ;-)

So for 2d shapes in Urho you can subscribe to start and end collision events within the `PhysicsWorld2D` component and them act upon them generically. i.e. if the two objs that are colliding are a baseball and a bat, recalc the baseball directional vector is a very unique test but if you have bullets from a machine gun, a hand gun and rocks from a slingshot colliding with a tin can, you can make the bullet/rock disappear and apply a bullet hole texture to the tin can in a couple of lines of code, so just one event for thousands of potential bullets and rock, instead of thousands of individually instanced events (that would kill performance and drive the garbage collector to drink).

Example:

```
var physics2d = scene.CreateComponent<PhysicsWorld2D>();
physics2d.PhysicsBeginContact2D += (PhysicsBeginContact2DEventArgs obj) =>
{
	D.WriteLine($"{obj.BodyB.Node.Name} is beginning contact w/ {obj.BodyA.Node.Name}");
};

```

Output:

```
RigidBody is beginning contact w/ RigidBody
RigidBody is beginning contact w/ RigidBody
RigidBody is beginning contact w/ Ground
RigidBody is beginning contact w/ RigidBody
RigidBody is beginning contact w/ Ground

```

**Comment by EgorBo** [comment]
Exactly! PS: physics for 2D and 3D is handled by different 3rd party engines: Bullet & Box2D.
