### ISSUE TITLE
NavigationMesh.FindPath

### ISSUE THREAD

**Issue by EgorBo** [xamarin/urho#24]
15_Navigation (Line 292)

```
navMesh->FindPath(currentPath_, jackNode_->GetPosition(), endPos_);
```

**Comment by utekai** [comment]
The issue is the start and end vectors must be passed as ref, to the dll's findpath call.

So the dll call for UWP needs defined as:

This is a bug in the SharpReality binding.

To make this work for UWP, requires the start and end Vector3 arguments must be passed in as ref. Here’s the changed dll call def:

[DllImport(Consts.NativeImport, CallingConvention = CallingConvention.Cdecl)]
internal extern static IntPtr urho_navigationmesh_findpath(IntPtr navMesh, ref Urho.Vector3 start, ref Urho.Vector3 end, out int count);
