### ISSUE TITLE
Xamarin.Forms UWP release build fails when referencing UrhoSharp

### ISSUE THREAD

**Issue by abrasat** [xamarin/urho#241]
Following error occurs when trying to generate build release of Xamarin.Forms UWP application (UrhoSharp.Forms latest version 1.5.20):

> .nuget\packages\microsoft.net.native.compiler\1.7.0\tools\Microsoft.NetNative.targets(697,5): error : ILT0042: Arrays of pointer types are not currently supported: 'Urho.RenderPathCommand*[]'.__Arrays of pointer types are not currently supported: 'Urho.RenderPathCommand*[]'.__Arrays of pointer types are not currently supported: 'Urho.RenderPathCommand*[]'.__

**Comment by abrasat** [comment]
If the "Compile with .NET Native tool chain" option is disabled in the project build settings, it is possible to generate the release build without error, but the urho scene is not displayed anymore. With the debug build everything works fine.
Any solution for getting the release build working correctly ?

**Comment by daniel-packard** [comment]
There is some additional info relevant to this issue here in the Xamarin forums: 
- https://forums.xamarin.com/discussion/88361/unable-to-execute-uwp-apps-release-build-with-urhosharp-referenced

**Comment by davejmurphy** [comment]
I don't think the issue @daniel-packard linked is related, the RenderPathCommand*[] was introduced in this commit: c9f83cd.

I'm experiencing the same error message when using .NET native with version 1.5.22. But for me the app works fine when compiled without .NET native. It seems that every version since then can't build .NET native.

This is a pretty big issue because apps need to compile with .NET native or they can't be published to the Windows Store.

**Comment by EgorBo** [comment]
@davejmurphy I temporarily removed this method for UWP (if someone needs it I can provide a workaround) in 1.7.3-pre

**Comment by davejmurphy** [comment]
@EgorBo Thanks for the quick reply. 

I just downloaded 1.7.3-pre and tested building a .NET native urhosharp project and a sharpreality project but I'm still getting the `Arrays of pointer types are not currently supported: 'Urho.RenderPathCommand*[]` error.

**Comment by FlammableFork** [comment]
This is simply a 'me too' comment.  I am in the same boat as @abrasat.  Everything works great in debug mode, however compiling a Release build with the 'Compile with .NET Native tool chain' option enabled I receive the error @davejmurphy mentioned.  If I compile a Release build with that option disabled, then compilation succeeds, but my scene no longer displays.

**Comment by OhPun** [comment]
Another me too. 1.7.3-pre

**Comment by OhPun** [comment]
@EgorBo how do I get the 1.7.3-pre where ` !WINDOWS_UWP && !UWP_HOLO` are compiled in. Because the 1.7.3-pre that I have still reports the _Arrays of pointer types are not currently supported: 'Urho.RenderPathCommand*[]_ error. 

Any response will be welcome, including one that tells me that you are not working on this.

**Comment by adrianimajion** [comment]
I also encountered this problem when building for Release x86 on UWP referencing UrhoSharp. I'm using the latest stable from NuGet. I don't encounter this bug when I target debug.

**Comment by EgorBo** [comment]
All issues have been fixed in recent updates (1.8.x)
