### ISSUE TITLE
2D/3D physics world consistency

### ISSUE THREAD

**Issue by Alan-FGR** [xamarin/urho#287]
Hey guys, I'm wondering if you're trying to keep the 2D and 3D physics API consistent, for example Gravity has a setter in the 2D version but not in the 3D (you got to use SetGravity()). I think it's important to clarify this so people can contribute if your goal is to keep things consistent.

**Comment by migueldeicaza** [comment]
Not clear in which class you are observing this, please reopen issue with the information.

It might be a bug in a specific class where the underlying API does not expose a getter, hence the lack of automatic property mapping.

**Comment by Alan-FGR** [comment]
I was actually just giving an example, in that specific case, the 2D world has a property with both getter and setter:
https://github.com/xamarin/urho/blob/58a8b9cc442a6e41ca54716c52a4c9cf0f223065/Bindings/Portable/Generated/PhysicsWorld2D.cs#L719-L726
but the 3D has only getter:
https://github.com/xamarin/urho/blob/58a8b9cc442a6e41ca54716c52a4c9cf0f223065/Bindings/Portable/Generated/PhysicsWorld.cs#L639-L643
although it has a SetGravity method too:
https://github.com/xamarin/urho/blob/58a8b9cc442a6e41ca54716c52a4c9cf0f223065/Bindings/Portable/Generated/PhysicsWorld.cs#L183

but my question wasn't about that specific case but in general since the Urho API isn't consistent between 3D and 2D but that doesn't mean UrhoSharp can't have consistent API although some methods are very different, see for example raycasting in which the 2D version takes start and end points while the 3D takes a Ray (position, direction) and distance.

In Atomic we decided to keep them consistent but that means Urho docs won't be as useful. Again in that specific case (raycasting) overloads could be provided so both 3D and 2D might take a Ray or start+end.

The question was about general development direction though.

**Comment by migueldeicaza** [comment]
I think we need to study why this binding was not auto-generated, it looks like the underlying API was correct, and we should have generated the proper property.  

It is hard to dictate a general policy without knowing the scope of the work.    At this point, the philosophy was to keep the binding close to the underlying Urho platform, and if changes need to be done to the bindings, to contribute upstream, so that both Urho and UrhoSharp benefit.

I am open to deviating when it makes sense, but we would need to document those scenarios first.   The above looks more like a generator bug that we should address.
